--------------------------------------------------------
--  File created - Monday-June-03-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRUEBAS_TEST
--------------------------------------------------------

create sequence ID_PROJECT_Sequence START WITH 1 
  INCREMENT BY 1;

create sequence ID_SERVICE_Sequence START WITH 1 
  INCREMENT BY 1;
  
create sequence ID_SERVICE_Dep_Sequence START WITH 1 
  INCREMENT BY 1;

CREATE TABLE "XML_USER"."PRUEBAS_TEST" 
   (	"ID_PROJECT" NUMBER, 
	"OSBPROJECTNAME" VARCHAR2(200 BYTE), 
	"CREATED_DATE" DATE, 
	"AMBIENTE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger PRUEBAS_TEST_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "XML_USER"."PRUEBAS_TEST_TRIGGER" 
BEFORE INSERT ON PRUEBAS_TEST
FOR EACH ROW
   WHEN (new.ID_PROJECT IS NULL) BEGIN
  :new.ID_PROJECT := ID_PROJECT_Sequence.NEXTVAL;
END;
/
ALTER TRIGGER "XML_USER"."PRUEBAS_TEST_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TEST_OSB_DATETRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "XML_USER"."TEST_OSB_DATETRIGGER" 
BEFORE INSERT ON PRUEBAS_TEST
FOR EACH ROW
   WHEN (new.CREATED_DATE IS NULL) BEGIN
  :new.CREATED_DATE := SYSDATE;
END;
/
ALTER TRIGGER "XML_USER"."TEST_OSB_DATETRIGGER" ENABLE;


--------------------------------------------------------
--  DDL for Table SERVICE_DEPENDENCIES
--------------------------------------------------------

  CREATE TABLE "XML_USER"."SERVICE_DEPENDENCIES" 
   (	"SERVICE" VARCHAR2(250 BYTE), 
	"DEPENDENTSERVICE" VARCHAR2(250 BYTE), 
	"ID_SERVICE_DEP" NUMBER, 
	"CREATED_DATE" DATE, 
	"AMBIENTE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger SERVICE_DEP_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "XML_USER"."SERVICE_DEP_TRIGGER" 
BEFORE INSERT ON SERVICE_DEPENDENCIES
FOR EACH ROW
   WHEN (new.ID_SERVICE_DEP IS NULL) BEGIN
  :new.ID_SERVICE_DEP := ID_SERVICE_Dep_Sequence.NEXTVAL;
END;
/
ALTER TRIGGER "XML_USER"."SERVICE_DEP_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SERVICE_DEP_DATE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "XML_USER"."SERVICE_DEP_DATE_TRIGGER" 
BEFORE INSERT ON SERVICE_DEPENDENCIES
FOR EACH ROW
   WHEN (new.CREATED_DATE IS NULL) BEGIN
  :new.CREATED_DATE := SYSDATE;
END;
/
ALTER TRIGGER "XML_USER"."SERVICE_DEP_DATE_TRIGGER" ENABLE;


--------------------------------------------------------
--  DDL for Table TEST_SERVICES_DEV
--------------------------------------------------------

  CREATE TABLE "XML_USER"."TEST_SERVICES_DEV" 
   (	"SERVICENAME" VARCHAR2(250 BYTE), 
	"SERVICEFULLPATH" VARCHAR2(250 BYTE), 
	"OSBPROJECTNAME" VARCHAR2(250 BYTE), 
	"ISPS" VARCHAR2(250 BYTE), 
	"TYPE" VARCHAR2(250 BYTE), 
	"SERVICE_URI" VARCHAR2(250 BYTE), 
	"ID_SERVICE" NUMBER, 
	"CREATED_DATE" DATE, 
	"AMBIENTE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TEST_SERVICES_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "XML_USER"."TEST_SERVICES_TRIGGER" 
BEFORE INSERT ON IZZI_SERVICES
FOR EACH ROW
   WHEN (new.ID_SERVICE IS NULL) BEGIN
  :new.ID_SERVICE := ID_SERVICE_Sequence.NEXTVAL;
END;
/
ALTER TRIGGER "XML_USER"."TEST_SERVICES_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger IZZI_SERVICE_DATE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "XML_USER"."SERVICE_DATE_TRIGGER" 
BEFORE INSERT ON IZZI_SERVICES
FOR EACH ROW
   WHEN (new.CREATED_DATE IS NULL) BEGIN
  :new.CREATED_DATE := SYSDATE;
END;
/
ALTER TRIGGER "XML_USER"."SERVICE_DATE_TRIGGER" ENABLE;

